### ISSUE TITLE
Back button not working correctly

### ISSUE THREAD

**Issue by billsaysthis** [cmpolis/Pagify#5]
Using Chrome latest on OS X 10.6.

My click path:

Click from GH to demo -> see About page
Click Usage -> see Usage page
Click  Options -> see Options page
Click Back -> see Usage page
Click Back -> see blank page (PROBLEM, should've seen About) (not totally blank, still see nav content above the Pagified divs)
Click Back -> see GH repo (starting point)

**Comment by cmpolis** [comment]
Thanks for reporting this! Just pushed out a fix.
